### ISSUE TITLE
Broken with apps using ember-cli 1.13

### ISSUE THREAD

**Issue by lukemelia** [zapnito/ember-cli-deploy-build#13]
The plugin is looking for Brocfile.js, but the app is using ember-cli-build.js. In general, it would be ideal if the plugin used the build mechanism in the app's version of ember-cli, not it's own. This may be only an issue with an `npm link`-ed setup only. I'll check tomorrow.

**Comment by achambers** [comment]
@lukemelia I haven't yet upgrades to 1.13. Is the Brocfile.js now called
ember-cli-build.js ?

**Comment by lukemelia** [comment]
Yep. I think we may be able to use `context.project.require(...)`to load the project's version of the build task

**Comment by achambers** [comment]
Cool. I'll look in to it. Nice find.
